//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOWIntegration.Campaign {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Campaign.CampaignSoap")]
    public interface CampaignSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PendingProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PendingProduct(string cGroupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PointsEarned", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PointsEarned(string cGroupCode, string cBillNo, string cMobileNo, string cPoints, string cBillDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedeemCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RedeemCoupon(string cGroupCode, string cCouponCode, string cRedeemedOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedeemMultipleCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RedeemMultipleCoupon(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedeemMultipleCoupon_New", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RedeemMultipleCoupon_New(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, short ibypassRedeem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedeemMultipleCoupon_Scheme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RedeemMultipleCoupon_Scheme(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, short ibypassRedeem, string cSchemeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedeemMultipleCoupon_SingleChannel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RedeemMultipleCoupon_SingleChannel(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, string cSchemeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convert_MultipleCoupon_Into_SingleeCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Convert_MultipleCoupon_Into_SingleeCoupon(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, string cDeptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register_Tab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Register_Tab(string cGroupCode, string cStoreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResendVoucher_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResendVoucher_NEW(string cGroupCode, string cMobile, string cCampaign, string cDeptid);
        
        // CODEGEN: Parameter 'bnData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RUNCMD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.RUNCMDResponse RUNCMD(WOWIntegration.Campaign.RUNCMDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveCustomer(string cGroupCode, System.Data.DataTable DtM, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCustomerJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveCustomerJson(string cGroupCode, string CustomerDetail, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FEEDBACKTINY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FEEDBACKTINY(string cGroupCode, string cCustomerId, string MEMOID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETAILTINYURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RETAILTINYURL(string cGroupCode, string CMID, string cIP, string cFolderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMemo_NEW_POS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SaveMemo_NEW_POS(string cGroupCode, System.Data.DataTable DtM, System.Data.DataTable DtD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMemo_NEW_POS_TINY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SaveMemo_NEW_POS_TINY(string cGroupCode, System.Data.DataTable DtM, System.Data.DataTable DtD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMemoARC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SaveMemoARC(string cGroupCode, System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMemoJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveMemoJson(string cGroupCode, string cMasterData, string cDetailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMemoWizClip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveMemoWizClip(string cGroupCode, string cMasterData, string cDetailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SENDSMSFORPOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SENDSMSFORPOS(string cGroupCode, string cMobile, string cEcouponID, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SENDSMSFORPOS_WHATSAPP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SENDSMSFORPOS_WHATSAPP(string cGroupCode, string cMobile, string cEcouponID, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SENDSMS_THROUGH_SOFTINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SENDSMS_THROUGH_SOFTINFO(string cSenderID, string cMobile, string cMsg, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SynchCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SynchCustomer(string cGroupCode, string cOldCustomerCode, string cNewCustomerCode, System.Data.DataTable DtM, int iMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TESTURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TESTURL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NEWURL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TicketResponse(string cActivationkey, string cTicketid, string cWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateCustomer(string cGroupCode, string cRegKey, string cCustomerName, string cCustMobile, string cCity, string cEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGCRedemptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateGCRedemptionInfo(string cGroupCode, string cVoucherCode, string cBillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upDateGiftCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upDateGiftCard(string cGroupCode, string cCardNo, string cXnid, string cXnDt, string cCCustCode, string cLocId, double iAmount, string cCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRedemptionInfo_NEW_POS_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UpdateRedemptionInfo_NEW_POS_1(string cGroupCode, string cVoucherCode, string cBillNo, double nAmount, string cBillID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRedemptionInfoJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateRedemptionInfoJson(string cGroupCode, string cVoucherCode, string cBillNo, double nAmount, string cBillID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateTable(string cGroupCode, string cTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPLOAD_EASYCUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPLOAD_EASYCUT(string cLOCID, string cHoId, string cMemoid, System.Data.DataSet Ds);
        
        // CODEGEN: Parameter 'bnData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPLOAD_EASYCUT_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWResponse UPLOAD_EASYCUT_NEW(WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPLOAD_LOCINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPLOAD_LOCINFO(string cGrpCode, System.Data.DataTable Dt, System.Data.DataTable DtAc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPLOAD_RFOPT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPLOAD_RFOPT(string cHoId, System.Data.DataSet Ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadCustomer(string cGroupCode, System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadCustomerAns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UploadCustomerAns(string cGroupCode, string cRegKey, string cCustMobileNo, string Answer_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadLocation(string cGroupCode, System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadLocation_Multi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadLocation_Multi(string cGroupCode, System.Data.DataTable DtM, string cHoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadMaster(string cGroupCode, System.Data.DataTable DtM, string cTName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadMissingBills", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadMissingBills(string cGroupCode, string cLocID, string cBillNo, string cBillDt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadProductsku", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadProductsku(string cGroupCode, System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPLOADSMSLOGBULK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPLOADSMSLOGBULK(string cSender, System.Data.DataTable DtSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadTiket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpLoadTiket(int iMode, string cActivationkey, string cTicket, string cSubJect, string cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate_RegKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Validate_RegKey(string cGroupCode, string cRegKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateBill(string cGroupCode, string cBillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDATEMOBILE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VALIDATEMOBILE(string cGroupCode, string cCustomer, ref int iPmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer2021", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateCustomer2021(string cGroupCode, System.Data.DataTable DtM, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACKRUNCMD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ACKRUNCMD(string cGroupCode, string cLOCID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECK(string GroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APK_MSG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string APK_MSG(string GroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APK_MSG_ACK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string APK_MSG_ACK(string GroupID, string cMobile, string cRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelBill(string cGroupCode, string cBillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECKCONNECTION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECKCONNECTION(string cGroupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckCustomer(string cGroupCode, string cRegKey, string cCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckGroupCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckGroupCode(ref System.Data.DataTable dtInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckRegistration(ref System.Data.DataTable dtInfo);
        
        // CODEGEN: Parameter 'CmpnByteArrayResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnByteArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.CmpnByteArrayResponse CmpnByteArray(WOWIntegration.Campaign.CmpnByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnGetJsonDT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CmpnGetJsonDT(string CommaSeparatedString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnGetPendingCoupons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CmpnGetPendingCoupons(string cGroupCode, string cCustCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnGetPointLedgerReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CmpnGetPointLedgerReport(string cGroupCode, string cMobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnGetStatCityFromCityCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CmpnGetStatCityFromCityCode(string cGroupCode, string cCityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CmpnUpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CmpnUpdateCustomer(string cGroupCode, string cCommaSeparatedParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateCoupon(string cGroupCode, string cCouponCode, string cCouponAmt, string cDiscountMode, string cExpiryDate, string cMobile, string cFirstName, string cLastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerDetail_json", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CustomerDetail_json(string cGroupCode, string cRegKey, string CMOOBILENO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DNDSERVICE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DNDSERVICE(string cGroupCode, string cMobile, string cInboxMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DownLoadData(string cGroupCode, string cTableName);
        
        // CODEGEN: Parameter 'DownloadUpdate_grpcodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadUpdate_grpcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.DownloadUpdate_grpcodeResponse DownloadUpdate_grpcode(WOWIntegration.Campaign.DownloadUpdate_grpcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ECOUPONDETAIL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ECOUPONDETAIL(string cGroupCode, string cECoupon, string cMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EcouponDetailJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EcouponDetailJson(string cGroupCode, string cECoupon, string cMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EditBill(string cGroupCode, string cBillNo, string cEditMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedBackQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FeedBackQuestion(string cGroupCode, string cRegKey, string nMode, string cLastQstnUpdateDt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedBackQuestion_js", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FeedBackQuestion_js(string cGroupCode, string cRegKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FLATDISCOUNT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FLATDISCOUNT(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GENERATEGIFTPASWORD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GENERATEGIFTPASWORD(string cGroupCode, double iMode, double iAmount, string cCardNo, string cMobile, string cPwd, string cLocId, string cCustName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GENMANUALCOUPON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GENMANUALCOUPON(string cGroupCode, string cCustomerName, string cMobile, double nAmount, string cXnid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCityState(string cGroupCode, string cID, string cMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETCONTACTDETAIL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETCONTACTDETAIL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCouponAmount_MAX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCouponAmount_MAX(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode, double nMaxBillAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCouponAmount_NEW_POS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCouponAmount_NEW_POS(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCouponAmountJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCouponAmountJson(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomer(string cGroupCode, string cID, int iMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomerAll(string cGroupCode, string cID, string dtlastUpdate, short iPrivilage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCustomerJson(string cGroupCode, string cID, int iMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETCUSTPROFILE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETCUSTPROFILE(string cGroupCode, string cCustomerCode, int nRowCount, int icouponType, int iProfileType, ref System.Data.DataTable Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GETDATE();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETDATE_STRING", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETDATE_STRING();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDemoPeriod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetDemoPeriod(out string cErrMsg, string cProductName, string cMasterkey, string cDeptID, string cGroupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDemoPeriodEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetDemoPeriodEncrypt(out string cErrMsg, string cProductName, string cMasterkey, string cDeptID);
        
        // CODEGEN: Parameter 'bnData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETEASYCUTDATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.GETEASYCUTDATAResponse GETEASYCUTDATA(WOWIntegration.Campaign.GETEASYCUTDATARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETGENERICCUSTOMERFLAG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETGENERICCUSTOMERFLAG(string cGroupCode, string cCustCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETINSTANT_COUPON_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GETINSTANT_COUPON_NEW(string cGroupCode, int nMode, string cCustomerCode, string cDeptID, string cMemoId, double dBillAmt, double dDiscAmt, double dAdjAmt, string cBillDt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETPURHISORY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETPURHISORY(string cGroupCode, string cCustomerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReginfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetReginfo(string cDatabase, string cActivationkey, string cMasterkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReginfoEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetReginfoEncrypt(out string cErrMsg, string cProductName, string cActivationkey, string cMasterkey, string cDeptID, string cGRPCODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReginfoEncryptNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetReginfoEncryptNew(out string cErrMsg, string cProductName, string cActivationkey, string cMasterkey, string cDeptID, string cDeptID_HO, string cGRPCODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETWIZCLIPID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETWIZCLIPID(string cGroupCode, string cHOID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_HISTORY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_HISTORY(string cGroupCode, int iMode, string cMobile, string cGV, ref System.Data.DataTable dtHis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_MOBILEVALIDATION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_MOBILEVALIDATION(string cGroupCode, string cDeptID, string cCustMobileNo, int iMode, ref string cOTP, ref string cSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_MOBILEVALIDATION_Multi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_MOBILEVALIDATION_Multi(string cGroupCode, string cDeptID, string cCustMobileNo, int iMode, ref string cOTP, ref string cSMS, string cOwnerMob, System.Data.DataTable DtM, ref System.Data.DataTable dtErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_SENDSMSFORVALIDATION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_SENDSMSFORVALIDATION(string cGroupCode, string cMobile, string cSMS, string cOTP, string cDeptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_UPLOADDATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_UPLOADDATA(string cGroupCode, ref System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GV_UPLOADDATA_SINGLECHANNEL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GV_UPLOADDATA_SINGLECHANNEL(string cGroupCode, ref System.Data.DataTable DtM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HandShake", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HandShake();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        // CODEGEN: Parameter 'bImg' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogAttendance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WOWIntegration.Campaign.LogAttendanceResponse LogAttendance(WOWIntegration.Campaign.LogAttendanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MERGE_EASYCUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MERGE_EASYCUT(string cLOCID, string cHoId, string cMemoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MIRROR_LOG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MIRROR_LOG(string cGroupCode, string cDeptid, string cXnType, string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WIZCLIP_LOG_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WIZCLIP_LOG_NEW(string cGroupCode, string cDeptid, string cError, string cMemoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WIZCLIP_LOG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WIZCLIP_LOG(string cGroupCode, string cDeptid, string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WIZCLIP_PENDING_LOG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WIZCLIP_PENDING_LOG(string cGroupCode, string cDeptid, string DtLastSynch, int iCount);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUNCMD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RUNCMDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cGroupCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cLOCID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cHoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bnData;
        
        public RUNCMDRequest() {
        }
        
        public RUNCMDRequest(string cGroupCode, string cLOCID, string cHoId, byte[] bnData) {
            this.cGroupCode = cGroupCode;
            this.cLOCID = cLOCID;
            this.cHoId = cHoId;
            this.bnData = bnData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUNCMDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RUNCMDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RUNCMDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bnData;
        
        public RUNCMDResponse() {
        }
        
        public RUNCMDResponse(string RUNCMDResult, byte[] bnData) {
            this.RUNCMDResult = RUNCMDResult;
            this.bnData = bnData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPLOAD_EASYCUT_NEW", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPLOAD_EASYCUT_NEWRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cLOCID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cHoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cMemoid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bnData;
        
        public UPLOAD_EASYCUT_NEWRequest() {
        }
        
        public UPLOAD_EASYCUT_NEWRequest(string cLOCID, string cHoId, string cMemoid, byte[] bnData) {
            this.cLOCID = cLOCID;
            this.cHoId = cHoId;
            this.cMemoid = cMemoid;
            this.bnData = bnData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPLOAD_EASYCUT_NEWResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPLOAD_EASYCUT_NEWResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UPLOAD_EASYCUT_NEWResult;
        
        public UPLOAD_EASYCUT_NEWResponse() {
        }
        
        public UPLOAD_EASYCUT_NEWResponse(string UPLOAD_EASYCUT_NEWResult) {
            this.UPLOAD_EASYCUT_NEWResult = UPLOAD_EASYCUT_NEWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CmpnByteArray", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CmpnByteArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string text;
        
        public CmpnByteArrayRequest() {
        }
        
        public CmpnByteArrayRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CmpnByteArrayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CmpnByteArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CmpnByteArrayResult;
        
        public CmpnByteArrayResponse() {
        }
        
        public CmpnByteArrayResponse(byte[] CmpnByteArrayResult) {
            this.CmpnByteArrayResult = CmpnByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadUpdate_grpcode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadUpdate_grpcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool bLocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string cGRPCODE;
        
        public DownloadUpdate_grpcodeRequest() {
        }
        
        public DownloadUpdate_grpcodeRequest(string FileName, string cDateTime, bool bLocType, string cGRPCODE) {
            this.FileName = FileName;
            this.cDateTime = cDateTime;
            this.bLocType = bLocType;
            this.cGRPCODE = cGRPCODE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadUpdate_grpcodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadUpdate_grpcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadUpdate_grpcodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cDateTime;
        
        public DownloadUpdate_grpcodeResponse() {
        }
        
        public DownloadUpdate_grpcodeResponse(byte[] DownloadUpdate_grpcodeResult, string cDateTime) {
            this.DownloadUpdate_grpcodeResult = DownloadUpdate_grpcodeResult;
            this.cDateTime = cDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETEASYCUTDATA", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GETEASYCUTDATARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cLOCID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cHoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int iMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string cFromDt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string cToDt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string cMemoid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bnData;
        
        public GETEASYCUTDATARequest() {
        }
        
        public GETEASYCUTDATARequest(string cLOCID, string cHoId, int iMode, string cFromDt, string cToDt, string cMemoid, byte[] bnData) {
            this.cLOCID = cLOCID;
            this.cHoId = cHoId;
            this.iMode = iMode;
            this.cFromDt = cFromDt;
            this.cToDt = cToDt;
            this.cMemoid = cMemoid;
            this.bnData = bnData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETEASYCUTDATAResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GETEASYCUTDATAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GETEASYCUTDATAResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bnData;
        
        public GETEASYCUTDATAResponse() {
        }
        
        public GETEASYCUTDATAResponse(string GETEASYCUTDATAResult, byte[] bnData) {
            this.GETEASYCUTDATAResult = GETEASYCUTDATAResult;
            this.bnData = bnData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogAttendance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogAttendanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cEmpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bImg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cIp;
        
        public LogAttendanceRequest() {
        }
        
        public LogAttendanceRequest(string cEmpCode, byte[] bImg, string cIp) {
            this.cEmpCode = cEmpCode;
            this.bImg = bImg;
            this.cIp = cIp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogAttendanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogAttendanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LogAttendanceResult;
        
        public LogAttendanceResponse() {
        }
        
        public LogAttendanceResponse(string LogAttendanceResult) {
            this.LogAttendanceResult = LogAttendanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CampaignSoapChannel : WOWIntegration.Campaign.CampaignSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampaignSoapClient : System.ServiceModel.ClientBase<WOWIntegration.Campaign.CampaignSoap>, WOWIntegration.Campaign.CampaignSoap {
        
        public CampaignSoapClient() {
        }
        
        public CampaignSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaignSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable PendingProduct(string cGroupCode) {
            return base.Channel.PendingProduct(cGroupCode);
        }
        
        public string PointsEarned(string cGroupCode, string cBillNo, string cMobileNo, string cPoints, string cBillDate) {
            return base.Channel.PointsEarned(cGroupCode, cBillNo, cMobileNo, cPoints, cBillDate);
        }
        
        public string RedeemCoupon(string cGroupCode, string cCouponCode, string cRedeemedOn) {
            return base.Channel.RedeemCoupon(cGroupCode, cCouponCode, cRedeemedOn);
        }
        
        public System.Data.DataTable RedeemMultipleCoupon(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo) {
            return base.Channel.RedeemMultipleCoupon(cGroupCode, dtCAMPAIGN_REDEMPTION_SKU, dtSKU, dtARTICLE, dtCOUPON, dtBillInfo);
        }
        
        public System.Data.DataTable RedeemMultipleCoupon_New(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, short ibypassRedeem) {
            return base.Channel.RedeemMultipleCoupon_New(cGroupCode, dtCAMPAIGN_REDEMPTION_SKU, dtSKU, dtARTICLE, dtCOUPON, dtBillInfo, ibypassRedeem);
        }
        
        public System.Data.DataTable RedeemMultipleCoupon_Scheme(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtSKU, System.Data.DataTable dtARTICLE, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, short ibypassRedeem, string cSchemeName) {
            return base.Channel.RedeemMultipleCoupon_Scheme(cGroupCode, dtCAMPAIGN_REDEMPTION_SKU, dtSKU, dtARTICLE, dtCOUPON, dtBillInfo, ibypassRedeem, cSchemeName);
        }
        
        public System.Data.DataTable RedeemMultipleCoupon_SingleChannel(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, System.Data.DataTable dtCOUPON, System.Data.DataTable dtBillInfo, string cSchemeName) {
            return base.Channel.RedeemMultipleCoupon_SingleChannel(cGroupCode, dtCAMPAIGN_REDEMPTION_SKU, dtCOUPON, dtBillInfo, cSchemeName);
        }
        
        public System.Data.DataTable Convert_MultipleCoupon_Into_SingleeCoupon(string cGroupCode, System.Data.DataTable dtCAMPAIGN_REDEMPTION_SKU, string cDeptID) {
            return base.Channel.Convert_MultipleCoupon_Into_SingleeCoupon(cGroupCode, dtCAMPAIGN_REDEMPTION_SKU, cDeptID);
        }
        
        public string Register_Tab(string cGroupCode, string cStoreID) {
            return base.Channel.Register_Tab(cGroupCode, cStoreID);
        }
        
        public System.Data.DataTable ResendVoucher_NEW(string cGroupCode, string cMobile, string cCampaign, string cDeptid) {
            return base.Channel.ResendVoucher_NEW(cGroupCode, cMobile, cCampaign, cDeptid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.RUNCMDResponse WOWIntegration.Campaign.CampaignSoap.RUNCMD(WOWIntegration.Campaign.RUNCMDRequest request) {
            return base.Channel.RUNCMD(request);
        }
        
        public string RUNCMD(string cGroupCode, string cLOCID, string cHoId, ref byte[] bnData) {
            WOWIntegration.Campaign.RUNCMDRequest inValue = new WOWIntegration.Campaign.RUNCMDRequest();
            inValue.cGroupCode = cGroupCode;
            inValue.cLOCID = cLOCID;
            inValue.cHoId = cHoId;
            inValue.bnData = bnData;
            WOWIntegration.Campaign.RUNCMDResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).RUNCMD(inValue);
            bnData = retVal.bnData;
            return retVal.RUNCMDResult;
        }
        
        public string SaveCustomer(string cGroupCode, System.Data.DataTable DtM, string cDeptid) {
            return base.Channel.SaveCustomer(cGroupCode, DtM, cDeptid);
        }
        
        public string SaveCustomerJson(string cGroupCode, string CustomerDetail, string cDeptid) {
            return base.Channel.SaveCustomerJson(cGroupCode, CustomerDetail, cDeptid);
        }
        
        public string FEEDBACKTINY(string cGroupCode, string cCustomerId, string MEMOID) {
            return base.Channel.FEEDBACKTINY(cGroupCode, cCustomerId, MEMOID);
        }
        
        public string RETAILTINYURL(string cGroupCode, string CMID, string cIP, string cFolderName) {
            return base.Channel.RETAILTINYURL(cGroupCode, CMID, cIP, cFolderName);
        }
        
        public System.Data.DataTable SaveMemo_NEW_POS(string cGroupCode, System.Data.DataTable DtM, System.Data.DataTable DtD) {
            return base.Channel.SaveMemo_NEW_POS(cGroupCode, DtM, DtD);
        }
        
        public System.Data.DataTable SaveMemo_NEW_POS_TINY(string cGroupCode, System.Data.DataTable DtM, System.Data.DataTable DtD) {
            return base.Channel.SaveMemo_NEW_POS_TINY(cGroupCode, DtM, DtD);
        }
        
        public System.Data.DataTable SaveMemoARC(string cGroupCode, System.Data.DataTable DtM) {
            return base.Channel.SaveMemoARC(cGroupCode, DtM);
        }
        
        public string SaveMemoJson(string cGroupCode, string cMasterData, string cDetailData) {
            return base.Channel.SaveMemoJson(cGroupCode, cMasterData, cDetailData);
        }
        
        public string SaveMemoWizClip(string cGroupCode, string cMasterData, string cDetailData) {
            return base.Channel.SaveMemoWizClip(cGroupCode, cMasterData, cDetailData);
        }
        
        public string SENDSMSFORPOS(string cGroupCode, string cMobile, string cEcouponID, string cDeptid) {
            return base.Channel.SENDSMSFORPOS(cGroupCode, cMobile, cEcouponID, cDeptid);
        }
        
        public string SENDSMSFORPOS_WHATSAPP(string cGroupCode, string cMobile, string cEcouponID, string cDeptid) {
            return base.Channel.SENDSMSFORPOS_WHATSAPP(cGroupCode, cMobile, cEcouponID, cDeptid);
        }
        
        public string SENDSMS_THROUGH_SOFTINFO(string cSenderID, string cMobile, string cMsg, string cDeptid) {
            return base.Channel.SENDSMS_THROUGH_SOFTINFO(cSenderID, cMobile, cMsg, cDeptid);
        }
        
        public string SynchCustomer(string cGroupCode, string cOldCustomerCode, string cNewCustomerCode, System.Data.DataTable DtM, int iMode) {
            return base.Channel.SynchCustomer(cGroupCode, cOldCustomerCode, cNewCustomerCode, DtM, iMode);
        }
        
        public string TESTURL() {
            return base.Channel.TESTURL();
        }
        
        public string NEWURL() {
            return base.Channel.NEWURL();
        }
        
        public System.Data.DataTable TicketResponse(string cActivationkey, string cTicketid, string cWhere) {
            return base.Channel.TicketResponse(cActivationkey, cTicketid, cWhere);
        }
        
        public string UpdateCustomer(string cGroupCode, string cRegKey, string cCustomerName, string cCustMobile, string cCity, string cEmail) {
            return base.Channel.UpdateCustomer(cGroupCode, cRegKey, cCustomerName, cCustMobile, cCity, cEmail);
        }
        
        public string UpdateGCRedemptionInfo(string cGroupCode, string cVoucherCode, string cBillNo) {
            return base.Channel.UpdateGCRedemptionInfo(cGroupCode, cVoucherCode, cBillNo);
        }
        
        public string upDateGiftCard(string cGroupCode, string cCardNo, string cXnid, string cXnDt, string cCCustCode, string cLocId, double iAmount, string cCustomer) {
            return base.Channel.upDateGiftCard(cGroupCode, cCardNo, cXnid, cXnDt, cCCustCode, cLocId, iAmount, cCustomer);
        }
        
        public System.Data.DataTable UpdateRedemptionInfo_NEW_POS_1(string cGroupCode, string cVoucherCode, string cBillNo, double nAmount, string cBillID) {
            return base.Channel.UpdateRedemptionInfo_NEW_POS_1(cGroupCode, cVoucherCode, cBillNo, nAmount, cBillID);
        }
        
        public string UpdateRedemptionInfoJson(string cGroupCode, string cVoucherCode, string cBillNo, double nAmount, string cBillID) {
            return base.Channel.UpdateRedemptionInfoJson(cGroupCode, cVoucherCode, cBillNo, nAmount, cBillID);
        }
        
        public string UpdateTable(string cGroupCode, string cTableName) {
            return base.Channel.UpdateTable(cGroupCode, cTableName);
        }
        
        public string UPLOAD_EASYCUT(string cLOCID, string cHoId, string cMemoid, System.Data.DataSet Ds) {
            return base.Channel.UPLOAD_EASYCUT(cLOCID, cHoId, cMemoid, Ds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWResponse WOWIntegration.Campaign.CampaignSoap.UPLOAD_EASYCUT_NEW(WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWRequest request) {
            return base.Channel.UPLOAD_EASYCUT_NEW(request);
        }
        
        public string UPLOAD_EASYCUT_NEW(string cLOCID, string cHoId, string cMemoid, byte[] bnData) {
            WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWRequest inValue = new WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWRequest();
            inValue.cLOCID = cLOCID;
            inValue.cHoId = cHoId;
            inValue.cMemoid = cMemoid;
            inValue.bnData = bnData;
            WOWIntegration.Campaign.UPLOAD_EASYCUT_NEWResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).UPLOAD_EASYCUT_NEW(inValue);
            return retVal.UPLOAD_EASYCUT_NEWResult;
        }
        
        public string UPLOAD_LOCINFO(string cGrpCode, System.Data.DataTable Dt, System.Data.DataTable DtAc) {
            return base.Channel.UPLOAD_LOCINFO(cGrpCode, Dt, DtAc);
        }
        
        public string UPLOAD_RFOPT(string cHoId, System.Data.DataSet Ds) {
            return base.Channel.UPLOAD_RFOPT(cHoId, Ds);
        }
        
        public string upLoadCustomer(string cGroupCode, System.Data.DataTable DtM) {
            return base.Channel.upLoadCustomer(cGroupCode, DtM);
        }
        
        public string UploadCustomerAns(string cGroupCode, string cRegKey, string cCustMobileNo, string Answer_Code) {
            return base.Channel.UploadCustomerAns(cGroupCode, cRegKey, cCustMobileNo, Answer_Code);
        }
        
        public string upLoadLocation(string cGroupCode, System.Data.DataTable DtM) {
            return base.Channel.upLoadLocation(cGroupCode, DtM);
        }
        
        public string upLoadLocation_Multi(string cGroupCode, System.Data.DataTable DtM, string cHoID) {
            return base.Channel.upLoadLocation_Multi(cGroupCode, DtM, cHoID);
        }
        
        public string upLoadMaster(string cGroupCode, System.Data.DataTable DtM, string cTName) {
            return base.Channel.upLoadMaster(cGroupCode, DtM, cTName);
        }
        
        public string upLoadMissingBills(string cGroupCode, string cLocID, string cBillNo, string cBillDt) {
            return base.Channel.upLoadMissingBills(cGroupCode, cLocID, cBillNo, cBillDt);
        }
        
        public string upLoadProductsku(string cGroupCode, System.Data.DataTable DtM) {
            return base.Channel.upLoadProductsku(cGroupCode, DtM);
        }
        
        public string UPLOADSMSLOGBULK(string cSender, System.Data.DataTable DtSMS) {
            return base.Channel.UPLOADSMSLOGBULK(cSender, DtSMS);
        }
        
        public string UpLoadTiket(int iMode, string cActivationkey, string cTicket, string cSubJect, string cDetails) {
            return base.Channel.UpLoadTiket(iMode, cActivationkey, cTicket, cSubJect, cDetails);
        }
        
        public string Validate_RegKey(string cGroupCode, string cRegKey) {
            return base.Channel.Validate_RegKey(cGroupCode, cRegKey);
        }
        
        public string ValidateBill(string cGroupCode, string cBillNo) {
            return base.Channel.ValidateBill(cGroupCode, cBillNo);
        }
        
        public string VALIDATEMOBILE(string cGroupCode, string cCustomer, ref int iPmode) {
            return base.Channel.VALIDATEMOBILE(cGroupCode, cCustomer, ref iPmode);
        }
        
        public string UpdateCustomer2021(string cGroupCode, System.Data.DataTable DtM, string cDeptid) {
            return base.Channel.UpdateCustomer2021(cGroupCode, DtM, cDeptid);
        }
        
        public string ACKRUNCMD(string cGroupCode, string cLOCID) {
            return base.Channel.ACKRUNCMD(cGroupCode, cLOCID);
        }
        
        public string CHECK(string GroupID) {
            return base.Channel.CHECK(GroupID);
        }
        
        public string APK_MSG(string GroupID) {
            return base.Channel.APK_MSG(GroupID);
        }
        
        public string APK_MSG_ACK(string GroupID, string cMobile, string cRowID) {
            return base.Channel.APK_MSG_ACK(GroupID, cMobile, cRowID);
        }
        
        public string CancelBill(string cGroupCode, string cBillNo) {
            return base.Channel.CancelBill(cGroupCode, cBillNo);
        }
        
        public string CHECKCONNECTION(string cGroupCode) {
            return base.Channel.CHECKCONNECTION(cGroupCode);
        }
        
        public string CheckCustomer(string cGroupCode, string cRegKey, string cCustomer) {
            return base.Channel.CheckCustomer(cGroupCode, cRegKey, cCustomer);
        }
        
        public string CheckGroupCode(ref System.Data.DataTable dtInfo) {
            return base.Channel.CheckGroupCode(ref dtInfo);
        }
        
        public string CheckRegistration(ref System.Data.DataTable dtInfo) {
            return base.Channel.CheckRegistration(ref dtInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.CmpnByteArrayResponse WOWIntegration.Campaign.CampaignSoap.CmpnByteArray(WOWIntegration.Campaign.CmpnByteArrayRequest request) {
            return base.Channel.CmpnByteArray(request);
        }
        
        public byte[] CmpnByteArray(string text) {
            WOWIntegration.Campaign.CmpnByteArrayRequest inValue = new WOWIntegration.Campaign.CmpnByteArrayRequest();
            inValue.text = text;
            WOWIntegration.Campaign.CmpnByteArrayResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).CmpnByteArray(inValue);
            return retVal.CmpnByteArrayResult;
        }
        
        public string CmpnGetJsonDT(string CommaSeparatedString) {
            return base.Channel.CmpnGetJsonDT(CommaSeparatedString);
        }
        
        public string CmpnGetPendingCoupons(string cGroupCode, string cCustCode) {
            return base.Channel.CmpnGetPendingCoupons(cGroupCode, cCustCode);
        }
        
        public string CmpnGetPointLedgerReport(string cGroupCode, string cMobileNo) {
            return base.Channel.CmpnGetPointLedgerReport(cGroupCode, cMobileNo);
        }
        
        public string CmpnGetStatCityFromCityCode(string cGroupCode, string cCityCode) {
            return base.Channel.CmpnGetStatCityFromCityCode(cGroupCode, cCityCode);
        }
        
        public string CmpnUpdateCustomer(string cGroupCode, string cCommaSeparatedParams) {
            return base.Channel.CmpnUpdateCustomer(cGroupCode, cCommaSeparatedParams);
        }
        
        public string CreateCoupon(string cGroupCode, string cCouponCode, string cCouponAmt, string cDiscountMode, string cExpiryDate, string cMobile, string cFirstName, string cLastName) {
            return base.Channel.CreateCoupon(cGroupCode, cCouponCode, cCouponAmt, cDiscountMode, cExpiryDate, cMobile, cFirstName, cLastName);
        }
        
        public string CustomerDetail_json(string cGroupCode, string cRegKey, string CMOOBILENO) {
            return base.Channel.CustomerDetail_json(cGroupCode, cRegKey, CMOOBILENO);
        }
        
        public string DNDSERVICE(string cGroupCode, string cMobile, string cInboxMsg) {
            return base.Channel.DNDSERVICE(cGroupCode, cMobile, cInboxMsg);
        }
        
        public System.Data.DataTable DownLoadData(string cGroupCode, string cTableName) {
            return base.Channel.DownLoadData(cGroupCode, cTableName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.DownloadUpdate_grpcodeResponse WOWIntegration.Campaign.CampaignSoap.DownloadUpdate_grpcode(WOWIntegration.Campaign.DownloadUpdate_grpcodeRequest request) {
            return base.Channel.DownloadUpdate_grpcode(request);
        }
        
        public byte[] DownloadUpdate_grpcode(string FileName, ref string cDateTime, bool bLocType, string cGRPCODE) {
            WOWIntegration.Campaign.DownloadUpdate_grpcodeRequest inValue = new WOWIntegration.Campaign.DownloadUpdate_grpcodeRequest();
            inValue.FileName = FileName;
            inValue.cDateTime = cDateTime;
            inValue.bLocType = bLocType;
            inValue.cGRPCODE = cGRPCODE;
            WOWIntegration.Campaign.DownloadUpdate_grpcodeResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).DownloadUpdate_grpcode(inValue);
            cDateTime = retVal.cDateTime;
            return retVal.DownloadUpdate_grpcodeResult;
        }
        
        public System.Data.DataTable ECOUPONDETAIL(string cGroupCode, string cECoupon, string cMobile) {
            return base.Channel.ECOUPONDETAIL(cGroupCode, cECoupon, cMobile);
        }
        
        public string EcouponDetailJson(string cGroupCode, string cECoupon, string cMobile) {
            return base.Channel.EcouponDetailJson(cGroupCode, cECoupon, cMobile);
        }
        
        public string EditBill(string cGroupCode, string cBillNo, string cEditMode) {
            return base.Channel.EditBill(cGroupCode, cBillNo, cEditMode);
        }
        
        public string FeedBackQuestion(string cGroupCode, string cRegKey, string nMode, string cLastQstnUpdateDt) {
            return base.Channel.FeedBackQuestion(cGroupCode, cRegKey, nMode, cLastQstnUpdateDt);
        }
        
        public string FeedBackQuestion_js(string cGroupCode, string cRegKey) {
            return base.Channel.FeedBackQuestion_js(cGroupCode, cRegKey);
        }
        
        public System.Data.DataTable FLATDISCOUNT(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode) {
            return base.Channel.FLATDISCOUNT(cGroupCode, cVoucherCode, cMobile, nAmount, cBillDt, cBillNo, cMode, iCamptype, cDeptid, iDiscMode);
        }
        
        public string GENERATEGIFTPASWORD(string cGroupCode, double iMode, double iAmount, string cCardNo, string cMobile, string cPwd, string cLocId, string cCustName) {
            return base.Channel.GENERATEGIFTPASWORD(cGroupCode, iMode, iAmount, cCardNo, cMobile, cPwd, cLocId, cCustName);
        }
        
        public string GENMANUALCOUPON(string cGroupCode, string cCustomerName, string cMobile, double nAmount, string cXnid) {
            return base.Channel.GENMANUALCOUPON(cGroupCode, cCustomerName, cMobile, nAmount, cXnid);
        }
        
        public System.Data.DataTable GetCityState(string cGroupCode, string cID, string cMode) {
            return base.Channel.GetCityState(cGroupCode, cID, cMode);
        }
        
        public string GETCONTACTDETAIL() {
            return base.Channel.GETCONTACTDETAIL();
        }
        
        public System.Data.DataTable GetCouponAmount_MAX(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode, double nMaxBillAmount) {
            return base.Channel.GetCouponAmount_MAX(cGroupCode, cVoucherCode, cMobile, nAmount, cBillDt, cBillNo, cMode, iCamptype, cDeptid, iDiscMode, nMaxBillAmount);
        }
        
        public System.Data.DataTable GetCouponAmount_NEW_POS(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode) {
            return base.Channel.GetCouponAmount_NEW_POS(cGroupCode, cVoucherCode, cMobile, nAmount, cBillDt, cBillNo, cMode, iCamptype, cDeptid, iDiscMode);
        }
        
        public string GetCouponAmountJson(string cGroupCode, string cVoucherCode, string cMobile, double nAmount, string cBillDt, string cBillNo, string cMode, short iCamptype, string cDeptid, short iDiscMode) {
            return base.Channel.GetCouponAmountJson(cGroupCode, cVoucherCode, cMobile, nAmount, cBillDt, cBillNo, cMode, iCamptype, cDeptid, iDiscMode);
        }
        
        public System.Data.DataTable GetCustomer(string cGroupCode, string cID, int iMode) {
            return base.Channel.GetCustomer(cGroupCode, cID, iMode);
        }
        
        public System.Data.DataTable GetCustomerAll(string cGroupCode, string cID, string dtlastUpdate, short iPrivilage) {
            return base.Channel.GetCustomerAll(cGroupCode, cID, dtlastUpdate, iPrivilage);
        }
        
        public string GetCustomerJson(string cGroupCode, string cID, int iMode) {
            return base.Channel.GetCustomerJson(cGroupCode, cID, iMode);
        }
        
        public string GETCUSTPROFILE(string cGroupCode, string cCustomerCode, int nRowCount, int icouponType, int iProfileType, ref System.Data.DataTable Dt) {
            return base.Channel.GETCUSTPROFILE(cGroupCode, cCustomerCode, nRowCount, icouponType, iProfileType, ref Dt);
        }
        
        public System.DateTime GETDATE() {
            return base.Channel.GETDATE();
        }
        
        public string GETDATE_STRING() {
            return base.Channel.GETDATE_STRING();
        }
        
        public bool GetDemoPeriod(out string cErrMsg, string cProductName, string cMasterkey, string cDeptID, string cGroupCode) {
            return base.Channel.GetDemoPeriod(out cErrMsg, cProductName, cMasterkey, cDeptID, cGroupCode);
        }
        
        public bool GetDemoPeriodEncrypt(out string cErrMsg, string cProductName, string cMasterkey, string cDeptID) {
            return base.Channel.GetDemoPeriodEncrypt(out cErrMsg, cProductName, cMasterkey, cDeptID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.GETEASYCUTDATAResponse WOWIntegration.Campaign.CampaignSoap.GETEASYCUTDATA(WOWIntegration.Campaign.GETEASYCUTDATARequest request) {
            return base.Channel.GETEASYCUTDATA(request);
        }
        
        public string GETEASYCUTDATA(string cLOCID, string cHoId, int iMode, string cFromDt, string cToDt, string cMemoid, ref byte[] bnData) {
            WOWIntegration.Campaign.GETEASYCUTDATARequest inValue = new WOWIntegration.Campaign.GETEASYCUTDATARequest();
            inValue.cLOCID = cLOCID;
            inValue.cHoId = cHoId;
            inValue.iMode = iMode;
            inValue.cFromDt = cFromDt;
            inValue.cToDt = cToDt;
            inValue.cMemoid = cMemoid;
            inValue.bnData = bnData;
            WOWIntegration.Campaign.GETEASYCUTDATAResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).GETEASYCUTDATA(inValue);
            bnData = retVal.bnData;
            return retVal.GETEASYCUTDATAResult;
        }
        
        public string GETGENERICCUSTOMERFLAG(string cGroupCode, string cCustCode) {
            return base.Channel.GETGENERICCUSTOMERFLAG(cGroupCode, cCustCode);
        }
        
        public System.Data.DataTable GETINSTANT_COUPON_NEW(string cGroupCode, int nMode, string cCustomerCode, string cDeptID, string cMemoId, double dBillAmt, double dDiscAmt, double dAdjAmt, string cBillDt) {
            return base.Channel.GETINSTANT_COUPON_NEW(cGroupCode, nMode, cCustomerCode, cDeptID, cMemoId, dBillAmt, dDiscAmt, dAdjAmt, cBillDt);
        }
        
        public string GETPURHISORY(string cGroupCode, string cCustomerCode) {
            return base.Channel.GETPURHISORY(cGroupCode, cCustomerCode);
        }
        
        public System.Data.DataTable GetReginfo(string cDatabase, string cActivationkey, string cMasterkey) {
            return base.Channel.GetReginfo(cDatabase, cActivationkey, cMasterkey);
        }
        
        public System.Data.DataTable GetReginfoEncrypt(out string cErrMsg, string cProductName, string cActivationkey, string cMasterkey, string cDeptID, string cGRPCODE) {
            return base.Channel.GetReginfoEncrypt(out cErrMsg, cProductName, cActivationkey, cMasterkey, cDeptID, cGRPCODE);
        }
        
        public System.Data.DataTable GetReginfoEncryptNew(out string cErrMsg, string cProductName, string cActivationkey, string cMasterkey, string cDeptID, string cDeptID_HO, string cGRPCODE) {
            return base.Channel.GetReginfoEncryptNew(out cErrMsg, cProductName, cActivationkey, cMasterkey, cDeptID, cDeptID_HO, cGRPCODE);
        }
        
        public string GETWIZCLIPID(string cGroupCode, string cHOID) {
            return base.Channel.GETWIZCLIPID(cGroupCode, cHOID);
        }
        
        public string GV_HISTORY(string cGroupCode, int iMode, string cMobile, string cGV, ref System.Data.DataTable dtHis) {
            return base.Channel.GV_HISTORY(cGroupCode, iMode, cMobile, cGV, ref dtHis);
        }
        
        public string GV_MOBILEVALIDATION(string cGroupCode, string cDeptID, string cCustMobileNo, int iMode, ref string cOTP, ref string cSMS) {
            return base.Channel.GV_MOBILEVALIDATION(cGroupCode, cDeptID, cCustMobileNo, iMode, ref cOTP, ref cSMS);
        }
        
        public string GV_MOBILEVALIDATION_Multi(string cGroupCode, string cDeptID, string cCustMobileNo, int iMode, ref string cOTP, ref string cSMS, string cOwnerMob, System.Data.DataTable DtM, ref System.Data.DataTable dtErr) {
            return base.Channel.GV_MOBILEVALIDATION_Multi(cGroupCode, cDeptID, cCustMobileNo, iMode, ref cOTP, ref cSMS, cOwnerMob, DtM, ref dtErr);
        }
        
        public string GV_SENDSMSFORVALIDATION(string cGroupCode, string cMobile, string cSMS, string cOTP, string cDeptid) {
            return base.Channel.GV_SENDSMSFORVALIDATION(cGroupCode, cMobile, cSMS, cOTP, cDeptid);
        }
        
        public string GV_UPLOADDATA(string cGroupCode, ref System.Data.DataTable DtM) {
            return base.Channel.GV_UPLOADDATA(cGroupCode, ref DtM);
        }
        
        public string GV_UPLOADDATA_SINGLECHANNEL(string cGroupCode, ref System.Data.DataTable DtM) {
            return base.Channel.GV_UPLOADDATA_SINGLECHANNEL(cGroupCode, ref DtM);
        }
        
        public string HandShake() {
            return base.Channel.HandShake();
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WOWIntegration.Campaign.LogAttendanceResponse WOWIntegration.Campaign.CampaignSoap.LogAttendance(WOWIntegration.Campaign.LogAttendanceRequest request) {
            return base.Channel.LogAttendance(request);
        }
        
        public string LogAttendance(string cEmpCode, byte[] bImg, string cIp) {
            WOWIntegration.Campaign.LogAttendanceRequest inValue = new WOWIntegration.Campaign.LogAttendanceRequest();
            inValue.cEmpCode = cEmpCode;
            inValue.bImg = bImg;
            inValue.cIp = cIp;
            WOWIntegration.Campaign.LogAttendanceResponse retVal = ((WOWIntegration.Campaign.CampaignSoap)(this)).LogAttendance(inValue);
            return retVal.LogAttendanceResult;
        }
        
        public string MERGE_EASYCUT(string cLOCID, string cHoId, string cMemoid) {
            return base.Channel.MERGE_EASYCUT(cLOCID, cHoId, cMemoid);
        }
        
        public string MIRROR_LOG(string cGroupCode, string cDeptid, string cXnType, string cError) {
            return base.Channel.MIRROR_LOG(cGroupCode, cDeptid, cXnType, cError);
        }
        
        public string WIZCLIP_LOG_NEW(string cGroupCode, string cDeptid, string cError, string cMemoid) {
            return base.Channel.WIZCLIP_LOG_NEW(cGroupCode, cDeptid, cError, cMemoid);
        }
        
        public string WIZCLIP_LOG(string cGroupCode, string cDeptid, string cError) {
            return base.Channel.WIZCLIP_LOG(cGroupCode, cDeptid, cError);
        }
        
        public string WIZCLIP_PENDING_LOG(string cGroupCode, string cDeptid, string DtLastSynch, int iCount) {
            return base.Channel.WIZCLIP_PENDING_LOG(cGroupCode, cDeptid, DtLastSynch, iCount);
        }
    }
}
